apiVersion: apps/v1
kind: Deployment
metadata:  
  name: hello-deployment  
  labels:    
    role: app
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
        version: v1.0.2
    spec:
      containers:
      - name: app
        image: "albertomurrodrigo/proyecto-mds:latest"
        resources:
        imagePullPolicy: Always
        ports:
        - containerPort: 8080